apiVersion: v1
kind: Namespace
metadata:
  managedFields:
  - apiVersion: v1
  name: gen3k8dev
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
---
apiVersion: v1
kind: Namespace
metadata:
  managedFields:
  - apiVersion: v1
  name: gen3elastic
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
