
def SAFE_BRANCH_NAME = env.BRANCH_NAME.replaceAll("[/_.\$%^&*()@!]","").toLowerCase()

pipeline {
    agent {
        label 'docker-slave'
    }

    environment {
        TAG = "${SAFE_BRANCH_NAME}"
    }

    stages {
        stage('Build and Push Docker Image') {
            steps {
                withDockerRegistry([credentialsId: 'gen3registryoptum', url: "https://gen3registryoptum.azurecr.io/"]) {
                    sh '''
                    cd projects/gen3-kubes/blobIndex/AzureIndexTrigger
                    docker build -t gen3registryoptum.azurecr.io/gen3/blobtriggerdocker:$TAG .
                    docker push gen3registryoptum.azurecr.io/gen3/blobtriggerdocker:$TAG
                    '''
                }
            }
        }
    }
}
