#!/usr/bin/groovy
@Library(['com.optum.jenkins.pipelines.templates.terraform', 'com.optum.jenkins.pipeline.library']) _

 withCredentials([azureServicePrincipal(
        credentialsId: 'Redbox-ServicePrincipal',
        clientIdVariable: 'TF_VAR_client_id',
        clientSecretVariable: 'TF_VAR_client_secret'
    )]) {
      AzurePipeline()
    }