---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-{{ .Values.ENV }}
  labels:
    {{- include "gen3kubernetes.labels" . | nindent 4 }}
    component: "spark"
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.spark.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gen3kubernetes.selectorLabels" . | nindent 6 }}
      component: "spark"
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gen3kubernetes.selectorLabels" . | nindent 8 }}
        component: "spark"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gen3kubernetes.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: spark-userspace
          persistentVolumeClaim:
            claimName: pvc-spark-{{ .Values.ENV }}
        - name: spark-startup
          configMap:
            defaultMode: 0775
            name: spark-configmap-{{ .Values.ENV }}
      containers:
        - name: "spark-{{ .Values.ENV }}"
          env:
            {{- range .Values.spark.environment }}
            - name:  {{ .name  | quote }}
              value: {{ .value | quote }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.spark.image }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          #command: ["sleep" , "60000000"]
          command: ["bash", "-c", "/gen3spark/startup/spark_startup.ksh"]
          volumeMounts:
            - name: "spark-userspace"
              mountPath: "/hadoop/hdfs/data"
              readOnly: False
            - name: "spark-startup"
              mountPath: "/gen3spark/startup"
              readOnly: False
          ports:
            {{- range .Values.spark.serviceports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: "TCP"
            {{- end }}
          livenessProbe:
            tcpSocket:
              port: "eightythirty"
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: "eightythirtyone"
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.spark.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-spark-{{ .Values.ENV }}
spec:
  storageClassName: gen3-azurefile
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.spark.userDirSize }}
