apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "gen3kubernetes.labels" . | nindent 4 }}
    component: "service-spark"
  name: service-spark-{{ .Values.ENV }}
spec:
  type: ClusterIP
  ports:
    {{- range .Values.spark.serviceports }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: "TCP"
    {{- end }}
  selector:
    {{- include "gen3kubernetes.selectorLabels" . | nindent 4 }}
    component: "spark"
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
