apiVersion: v1
data:
  jwt_private_key.pem: |
    -----BEGIN PRIVATE KEY-----
    MIIEwAIBADANBgkqhkiG9w0BAQEFAASCBKowggSmAgEAAoIBAQDkS+nTVWUnXgIQ
    11LICu8p5XOOKk4XliZWcOef8ik5hC2nydh6BgUeMsP/8hUb9q+MpKrpnI0Q1itR
    rI17HNlF47uN7oMsMBEXUbOQt7dT6ACoKhXUKHHegXX6ILVVSPxJgzgO4U3LkK03
    DF8V0XtE0O7ireOaecyObl1S4I61gxyWGllyCnvQoRVHF07ZbPK46xQD9Hs9lyIq
    SVq/Y4K4qchY26g4ZQ78lpPCCF3sd4wwI9DIGOTigKLgI+G6MxUSRo3z8C452Djv
    4BFHBdrbu6fTmxn5WumdN1cjksA7cyUYCEQ/zr3bVlIPEi0C3TlM6J485VDl/e+z
    NZDxE+CrAgMBAAECggEBALjXFfy72WikXrvP+wBoife8BXGHoy7JrUSzqXYBFYuy
    D10YuiMiGKa4p6TlFl5Lvxr6gD8hN734CZ7ZPLv/QZOqrUJfaOkwCcZ9qgt0FATl
    hRKi8IWUMY3b9++K6AajT1Ed4xd5KAm3m+dEJwB9WXcAS0pRTETYdNylUv41PpaK
    h+MwyBBF5NSGnRYQuLpSqTD8jRfaXOzsfUXQmElgQ0ywTVEQPyoWHaB2CQzWdRbv
    ChwPBOfJHh4wsEO2C+sLTcQ0/DL4wC6yahF6iqnfBNR0bmcsl1696RkZ+ricEPY8
    8pbefY9Kp4GvFd2bFjJfArCY8OhqtqeniKjUeOkOJnECgYEA9h1bG+g6G2SJZFhN
    1fEpT5tO4r0RA4ZBnlPVIaxOcBLgJGMsTsN/Olse1so4Mm0gFiT17icoRRde5XKj
    DPp6E2PSyafQgLF48OpEFpDNJRcSUx+SPchO5XbXS0E1g41SSV1iUGX5l8z5ooHZ
    oRh3nDR5FpqFmrskGZGGzYSVVgcCgYEA7XdYPW1W92s3l8ixfZAQmIhFvHt9BP3t
    +rQQth4DF+RiGw+9VurVGbcmnuDBFD79whU1dv07vimaJhRwzkJsYRWY7GipQjfb
    eJiP3noAykji8QLBuXLMn1nC0zPgPDI+fw9kGG6BN47TwffqegnY3e34x+Z6niOu
    RPChgbwuVz0CgYEAn+7bsfrrJ7nhfo/TpN+elNi8HqP2Vm/8XELmEYfDQRlDBuJb
    fKOWHfnwxGuMsVgwrbM/DY/sn1lclYY1Zs2uXsNTyy9+UuMBUK0rqe5XIW8ovVOa
    2QM+IedkaMbrW52Oh5ZjuRNLatYMswnmvsUDlUKUHZg0kiRihSsIiq1JzikCgYEA
    pJtm8mW5tBaBWdjHmCdmKaXE2WusdOpkrbVmJCfXsxcgHmwhrn9oKsQ3pEhd7t/f
    XUsAXbQaVq5V6XGf5IpMwFuNPssqEPnRS95NVEW0CITPs4taqGd4ijlZgLfkBzY4
    9jDADOOE9PMvvLRSuDfdObG9Eyyj8L0BD07SVbERWm0CgYEA36QYn6P84onE9lQ8
    JpXhzhf/fdywKF1aXABhK5qhoGSHUxLiQ9G2VIXO4JYshZj0O0wa7nJctKgl0Hs5
    fv6xmI5lSSi/Mzcw5FwB+zd9XwjuCx7/TvE5Q4yzj30ihC2gmtDEE/X0Wcy+o2Dc
    D8OEKlWXGVIdG6KbKLcdbNoOFjo=
    -----END PRIVATE KEY-----
  jwt_private_key.pem: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5Evp01VlJ14CENdSyArv
    KeVzjipOF5YmVnDnn/IpOYQtp8nYegYFHjLD//IVG/avjKSq6ZyNENYrUayNexzZ
    ReO7je6DLDARF1GzkLe3U+gAqCoV1Chx3oF1+iC1VUj8SYM4DuFNy5CtNwxfFdF7
    RNDu4q3jmnnMjm5dUuCOtYMclhpZcgp70KEVRxdO2WzyuOsUA/R7PZciKklav2OC
    uKnIWNuoOGUO/JaTwghd7HeMMCPQyBjk4oCi4CPhujMVEkaN8/AuOdg47+ARRwXa
    27un05sZ+VrpnTdXI5LAO3MlGAhEP86921ZSDxItAt05TOiePOVQ5f3vszWQ8RPg
    qwIDAQAB
    -----END PUBLIC KEY-----
kind: Secret
metadata:
  labels:
    {{- include "gen3kubernetes.labels" . | nindent 4 }}
  name: fence-jwt-secrets-conf-{{ .Values.ENV }}
type: Opaque
