apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    component: fence-config
    environment: {{ .Values.ENV }}
    {{- include "gen3kubernetes.labels" . | nindent 4 }}
  name: fence-config-configmap-{{ .Values.ENV }}
data:
  fence-config.yaml: |
    APP_NAME: 'Gen3 Data Commons'
    #BASE_URL: 'https://optumgen3public-ikveofnt.eastus.cloudapp.azure.com/user'
    BASE_URL: '{{ .Values.fence.base_url }}'
    DB: 'postgresql://{{ .Values.database.username }}:$$_FENCE$$_PASS$$@{{ .Values.database.servername }}:{{ .Values.database.port }}/{{ .Values.database.databasename }}'

    DEBUG: true
    MOCK_AUTH: false
    MOCK_GOOGLE_AUTH: false
    MOCK_STORAGE: true
    AUTHLIB_INSECURE_TRANSPORT: false

    SESSION_COOKIE_SECURE: true

    ENABLE_CSRF_PROTECTION: true

    OPENID_CONNECT:
      # These Google values must be obtained from Google's Cloud Console
      # Follow: https://developers.google.com/identity/protocols/OpenIDConnect
      #
      # You'll need to obtain a Client ID and Client Secret. Set the redirect URIs
      # in Google to be '{{ .Values.fence.base_url }}/login/google/login', but expand BASE_URL to
      # whatever you set it to above.
      {{- if .Values.fence.googleOauth.client_id }}
      google:
        client_id: '{{ .Values.fence.googleOauth.client_id }}'
        client_secret: '{{ .Values.fence.googleOauth.client_secret }}'
        redirect_url: '{{ .Values.fence.base_url }}/login/google/login/'
      {{- end }}
      {{- if .Values.fence.microsoftOauth.client_id }}
      microsoft:
        client_id: '{{ .Values.fence.microsoftOauth.client_id }}'
        client_secret: '{{ .Values.fence.microsoftOauth.client_secret }}'
        redirect_url: '{{ .Values.fence.base_url }}/login/microsoft/login/'
      {{- end }}
      {{- if .Values.fence.oktaOauth.client_id }}
      okta:
        client_id: '{{ .Values.fence.oktaOauth.client_id }}'
        client_secret: '{{ .Values.fence.oktaOauth.client_secret }}'
        redirect_url: '{{ .Values.fence.base_url }}/login/okta/login/'
        discovery_url: '{{ .Values.fence.oktaOauth.discovery_url }}'
      {{- end }}
    #
    DEFAULT_LOGIN_URL: '{{ .Values.fence.base_url }}/{{ .Values.fence.defaultLoginURLSuffix }}'
    #
    ENABLED_IDENTITY_PROVIDERS:
      # ID for which of the providers to default to
      default: {{ .Values.fence.defaultIDPProvider  | quote }}
      providers:
      {{- range .Values.fence.enabledIDPProviders }}
        {{ .name  }}:
          name: {{ .loginButtonText | quote }}
      {{- end }}
    OAUTH2_JWT_ALG: 'RS256'
    OAUTH2_JWT_ENABLED: true
    OAUTH2_JWT_ISS: '{{ .Values.fence.base_url }}'
    OAUTH2_PROVIDER_ERROR_URI: '/api/oauth2/errors'

    APPLICATION_ROOT: '/user'
    ACCESS_TOKEN_COOKIE_NAME: "access_token"

    SESSION_COOKIE_NAME: "fence"

    OAUTH2_TOKEN_EXPIRES_IN:
      "authorization_code": 1200
      "implicit": 1200
    ACCESS_TOKEN_EXPIRES_IN: 1200
    REFRESH_TOKEN_EXPIRES_IN: 2592000
    SESSION_TIMEOUT: 1800
    SESSION_LIFETIME: 28800
    GOOGLE_SERVICE_ACCOUNT_KEY_FOR_URL_SIGNING_EXPIRES_IN: 2592000
    GOOGLE_USER_SERVICE_ACCOUNT_ACCESS_EXPIRES_IN: 604800
    GOOGLE_ACCOUNT_ACCESS_EXPIRES_IN: 86400
    MAX_PRESIGNED_URL_TTL: 3600
    MAX_API_KEY_TTL: 2592000
    MAX_ACCESS_TOKEN_TTL: 3600

    SUPPORT_EMAIL_FOR_ERRORS: null
    SHIBBOLETH_HEADER: 'persistent_id'
    SSO_URL: 'https://auth.nih.gov/affwebservices/public/saml2sso?SPID={{ .Values.fence.base_url }}/shibboleth&RelayState='
    ITRUST_GLOBAL_LOGOUT: 'https://auth.nih.gov/siteminderagent/smlogout.asp?mode=nih&AppReturnUrl='
    dbGaP:
      info:
        host: ''
        username: ''
        password: ''
        port: 22
        proxy: ''
        proxy_user: ''
      protocol: 'sftp'
      decrypt_key: ''
      parse_consent_code: true

    STORAGE_CREDENTIALS: []
    AWS_CREDENTIALS:
      {{- range .Values.fence.amazonStorageCreds }}
      {{ .name | quote }}:
        aws_access_key_id: {{ .accesskeyid | quote }}
        aws_secret_access_key: {{ .secretkey | quote }}
      {{- end }}
    S3_BUCKETS:
      {{- range .Values.fence.amazonBuckets }}
      {{ .name | quote }}:
        cred: {{ .credentialname | quote }}
        {{- if .endpoint_url }}
        endpoint_url: {{ .endpoint_url | quote }}
        {{- end }}
        region: {{ .region | quote }}
      {{- end }}
    AZ_CREDENTIALS:
      {{- range .Values.fence.azCredentials }}
      {{ .name | quote }}:
        az_stgacctname: {{ .az_stgacctname | quote }}
        az_secret_access_key: {{ .az_secret_access_key | quote }}
      {{- end }}
    AZ_CONTAINERS:
      {{- range .Values.fence.azureBlobstores }}
      {{ .name | quote }}:
        cred: {{ .credentialname | quote }}
      {{- end }}

    DATA_UPLOAD_BUCKET: {{ .Values.fence.dataUploadBucket}}

    HTTP_PROXY:
      host: null
      port: 3128
    INDEXD: http://indexd-service-{{ .Values.ENV }}

    INDEXD_USERNAME: 'indexd_client'
    INDEXD_PASSWORD: 'indexd_client_pass'
    ARBORIST: http://arborist-service-{{ .Values.ENV }}
    CIRRUS_CFG:
      GOOGLE_API_KEY: ''
      GOOGLE_PROJECT_ID: ''
      GOOGLE_APPLICATION_CREDENTIALS: ''
      GOOGLE_STORAGE_CREDS: ''
      GOOGLE_ADMIN_EMAIL: ''
      GOOGLE_IDENTITY_DOMAIN: ''
      GOOGLE_CLOUD_IDENTITY_ADMIN_EMAIL: ''

    GOOGLE_GROUP_PREFIX: ''

    GUN_MAIL:
      'datacommons.io':
        smtp_hostname: 'smtp.mailgun.org'
        api_key: ''
        default_login: 'postmaster@mailgun.example.com'
        api_url: 'https://api.mailgun.net/v3/mailgun.example.com'
        smtp_password: ''

    EMAIL_SERVER: 'localhost'
    SEND_FROM: 'example@gmail.com'
    SEND_TO: 'example@gmail.com'

    WHITE_LISTED_GOOGLE_PARENT_ORGS: []
    WHITE_LISTED_SERVICE_ACCOUNT_EMAILS: []
    REMOVE_SERVICE_ACCOUNT_EMAIL_NOTIFICATION:
      enable: false
      domain: 'example.com'
      from: 'do-not-reply@example.com'
      subject: 'User service account removal notification'
      content: >
        Service accounts were removed from access control data because some users or
        service accounts of GCP Project {} are not authorized to access the data sets
        associated to the service accounts, or do not adhere to the security policies.
      admin:
        - 'admin@example.edu'

    GOOGLE_MANAGED_SERVICE_ACCOUNT_DOMAINS:
      - 'dataflow-service-producer-prod.iam.gserviceaccount.com'
      - 'cloudbuild.gserviceaccount.com'
      - 'cloud-ml.google.com.iam.gserviceaccount.com'
      - 'container-engine-robot.iam.gserviceaccount.com'
      - 'dataflow-service-producer-prod.iam.gserviceaccount.com'
      - 'sourcerepo-service-accounts.iam.gserviceaccount.com'
      - 'dataproc-accounts.iam.gserviceaccount.com'
      - 'gae-api-prod.google.com.iam.gserviceaccount.com'
      - 'genomics-api.google.com.iam.gserviceaccount.com'
      - 'containerregistry.iam.gserviceaccount.com'
      - 'container-analysis.iam.gserviceaccount.com'
      - 'cloudservices.gserviceaccount.com'
      - 'stackdriver-service.iam.gserviceaccount.com'
      - 'appspot.gserviceaccount.com'
      - 'partnercontent.gserviceaccount.com'
      - 'trifacta-gcloud-prod.iam.gserviceaccount.com'
      - 'gcf-admin-robot.iam.gserviceaccount.com'
      - 'compute-system.iam.gserviceaccount.com'
      - 'gcp-sa-websecurityscanner.iam.gserviceaccount.com'
      - 'storage-transfer-service.iam.gserviceaccount.com'
