---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin-manage-namespaces
  namespace: default
rules:
  - apiGroups: ["", "extensions", "apps","networking.k8s.io"]
    resources: ["namespaces", "roles", "persistentvolumeclaims", "persistentvolumes", \
                "rolebindings", "clusterroles", "clusterrolebindings", "secrets", \
                "storageclasses", "pods", "pods/logs", "deployments", "services", "endpoints", \
                "nodes", "ingresses", "statefulsets", "replicasets", "configmaps" ,\
                "networkpolicies", ]
    verbs: ["*"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets", "podsecuritypolicies"]
    verbs: ["*"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterrolebindings", "clusterroles", "rolebindings","roles" ]
    verbs: ["*"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations", "validatingwebhookconfigurations" ]
    verbs: ["*"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user-view-namespaces
  namespace: default
rules:
  - apiGroups: ["", "extensions", "apps","networking.k8s.io"]
    resources: ["namespaces", "roles",  "persistentvolumeclaims", \
                "persistentvolumes", "rolebindings", "clusterroles", "clusterrolebindings", \
                "storageclasses", "pods", "pods/logs", "deployments", "services", "endpoints", \
                "nodes", "ingresses", "statefulsets", "replicasets", "configmaps"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets", "podsecuritypolicies"]
    verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "admin-manage-namespaces"
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "admin-manage-namespaces"
subjects:
  - kind: User
    name: "rolinge2@entid.optumhub.net"
  - kind: User
    name: "cgarc139@entid.optumhub.net"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "user-view-namespaces"
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "user-view-namespaces"
subjects:
  - kind: Group
    name: "c1a150d8-6037-46d0-b603-bcb11b80f612"
  - kind: Group
    name: "26a01eec-7c1d-46f3-ba32-d2eb1081f37f"
