apiVersion: v1
# Useful pod for connecting and debugging network connections...
kind: Pod
metadata:
  name: "jumpserver-{{ .Values.ENV }}"
  labels:
    {{- include "gen3kubernetes.labels" . | nindent 4 }}
spec:
  restartPolicy: 'Never'
  containers:
    - name: jump
      image: centos:7
      command: ['sleep']
      args: ['60000000']
      env:
        - name: "DBHOST"
          value: {{ quote .Values.database_servername }}
        - name: "DBUSER"
          value: {{ quote .Values.fence.database.username }}
        - name:  "DBPASS"
          value: {{ quote .Values.fence.database.db_password }}
        - name: "DBFENCE"
          value: {{ quote .Values.fence.database.databasename }}
        - name:  "FENCECONNECT"
          value: "echo $DBPASS | psql -h {{  .Values.database_servername }} -U {{  .Values.fence.database.username }}@{{  .Values.database_servername }} {{  .Values.fence.database.databasename }}"
      resources:
        limits:
          cpu: '200m'
          memory: '720Mi'
        requests:
          cpu: '100m'
          memory: '512Mi'
