apiVersion: v1
# Useful pod for connecting and debugging network connections...
kind: Pod
metadata:
  name: "jumpserver-{{ .Values.ENV }}"
  labels:
    {{- include "gen3kubernetes.labels" . | nindent 4 }}
spec:
  restartPolicy: 'Never'
  containers:
    - name: jump
      image: {{ .Values.jupmserver.image }}
      command: ['sleep']
      args: ['60000000']
      env:
        - name: "DBHOST"
          value: {{ quote .Values.database_servername }}
        - name: "DBUSER"
          value: {{ quote .Values.fence.database.username }}
        - name:  "DBPASSFENCE"
          value: {{ quote .Values.fence.database.db_password }}
        - name:  "DBPASSARBORIST"
          value: {{ quote .Values.arborist.database.db_password }}
        - name: "DBFENCE"
          value: {{ quote .Values.fence.database.databasename }}
        - name: "DBARBORIST"
          value: {{ quote .Values.fence.database.databasename }}
        - name:  "FENCECONNECT"
          value: "echo $DBPASS | psql -h {{  .Values.database_servername }} -U {{  .Values.fence.database.username }}@{{  .Values.database_servername }} {{  .Values.fence.database.databasename }}"
      resources:
        {{- toYaml .Values.fence.resources | nindent 8 }}
