
def SAFE_BRANCH_NAME = env.BRANCH_NAME.replaceAll("[/_.\$%^&*()@!]","").toLowerCase()

pipeline {
    agent {
        label 'docker-slave'
    }

    environment {
        TAG = "${SAFE_BRANCH_NAME}"

    }
    stages {
        
        stage('Build and Push Docker Image') {
            steps {
                withDockerRegistry([credentialsId: 'gen3registryoptum', url: "https://gen3registryoptum.azurecr.io/"]) {
                    sh '''
                    cd projects/gen3-kubes/jupyterContainer
                    docker build -t gen3registryoptum.azurecr.io/jupyter-slim:$TAG-${BUILD_NUMBER} .
                    docker push gen3registryoptum.azurecr.io/jupyter-slim:$TAG-${BUILD_NUMBER}
                    '''
                    }
                }
        }
    }
}