apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "gen3kubernetes.labels" . | nindent 4 }}
    component: tube-configmap
  name: tube-config-configmap-{{ .Values.ENV }}
data:
  creds.json: |
    {
      "db_host": {{ .Values.database_servername | quote }},
      "db_username": "{{ .Values.sheepdog.database.username }}@{{ .Values.database_servername}}",
      "db_password": {{ .Values.sheepdog.database.db_password | quote }},
      "db_database": {{ .Values.sheepdog.database.databasename | quote }}
    }
  etlMapping.yaml: |
{{ .Files.Get  .Values.tube.etlmappinglocation  | indent 4}}
  tube_startup.ksh: |
{{ .Files.Get  .Values.tube.startupfileLocation  | indent 4}}
  es-root-ca.pem: |
{{ .Files.Get  .Values.tube.esrootcalocation  | indent 4}}
  run_etl_bespoke.py: |
{{ .Files.Get  .Values.tube.extrarunetllocation  | indent 4}}
  schemas.tar.gz.base64: |
{{ .Files.Get  .Values.sheepdog.schemas | b64enc | indent 4}}
